"""
FOREMAN Brainstorm Agent — v0.1
Generates new draft issues from VISION.md when the pipeline is dry.

Usage:
  python brainstorm_agent.py --force      # Run even if pipeline isn't dry
  python brainstorm_agent.py --dry-run    # Log actions without touching GitHub
"""

import os
import json
import logging
import argparse
from pathlib import Path
from datetime import datetime, timezone

from github import Github

# ─── Configuration ────────────────────────────────────────────

GITHUB_TOKEN = os.environ.get("GITHUB_TOKEN")
REPO_NAME = os.environ.get("FOREMAN_REPO", "")

# Agent behavior
BRAINSTORM_THRESHOLD = int(os.environ.get("BRAINSTORM_THRESHOLD", "3"))
BRAINSTORM_MAX_DRAFTS = int(os.environ.get("BRAINSTORM_MAX_DRAFTS", "5"))
COST_CEILING_USD = float(os.environ.get("COST_CEILING_USD", "5.0"))
ROUTING_PROFILE = os.environ.get("ROUTING_PROFILE", "balanced")

# Labels
LABEL_DRAFT = "draft"
LABEL_NEEDS_REFINEMENT = "needs-refinement"
LABEL_READY = "ready"
LABEL_IMPLEMENTING = "foreman-implementing"

# ─── Logging ──────────────────────────────────────────────────

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(message)s",
    datefmt="%H:%M:%S",
)
log = logging.getLogger("foreman.brainstorm")

# ─── Imports from internal modules ───────────────────────────

try:
    from cost_monitor import CostTracker
    from llm_client import LLMClient, ModelRouter
    from telegram_notifier import notify as tg
    from agent_state import agent_state_manager as state, AgentState
except ImportError as e:
    log.error(f"Failed to import internal modules: {e}")
    sys.exit(1)

# ─── Vision Loader ───────────────────────────────────────────

def load_vision() -> str:
    """Load VISION.md from repo root."""
    paths = [
        Path(__file__).parent / "VISION.md",
        Path.cwd() / "VISION.md",
    ]
    for p in paths:
        if p.exists():
            log.info(f"📖 Loaded VISION.md from {p}")
            return p.read_text()
    log.warning("⚠️  VISION.md not found, brainstorm mode will be limited")
    return ""

# ─── GitHub Helpers ──────────────────────────────────────────

class GitHubClient:
    def __init__(self, token: str, repo_name: str, dry_run: bool = False):
        self.gh = Github(token)
        self.repo = self.gh.get_repo(repo_name)
        self.dry_run = dry_run

    def get_all_open_issues(self) -> list:
        try:
            return list(self.repo.get_issues(state="open"))
        except Exception as e:
            log.error(f"Error fetching open issues: {e}")
            raise

    def get_closed_issues(self, count: int = 50) -> list:
        try:
            return list(self.repo.get_issues(state="closed", sort="updated", direction="desc")[:count])
        except Exception as e:
            log.error(f"Error fetching closed issues: {e}")
            return []

    def create_draft_issues(self, drafts: list[dict]) -> list[tuple[int, str]]:
        created = []
        for draft in drafts:
            try:
                title = draft.get("title", "Untitled Task")
                body = draft.get("body", "")
                
                if self.dry_run:
                    log.info(f"  [DRY RUN] Would create draft: {title}")
                    created.append((-1, title))
                    continue

                issue = self.repo.create_issue(
                    title=title,
                    body=body + "\n\n---\n_Auto-generated by FOREMAN brainstorm mode_",
                    labels=[self.repo.get_label(LABEL_DRAFT)],
                )
                log.info(f"  📝 Created draft #{issue.number}: {title}")
                created.append((issue.number, title))
            except Exception as e:
                log.error(f"Error creating draft issue: {e}")
        return created

# ─── Prompt ──────────────────────────────────────────────────

BRAINSTORM_SYSTEM = """You are FOREMAN, an autonomous agent that generates new development tasks
for a self-improving dev pipeline project.

You have access to:
1. VISION.md — the project's north star (goals, roadmap, architecture)
2. A list of existing open issues — so you don't create duplicates
3. A list of recently completed issues — so you know what's done

Your job: identify GAPS between the vision and current state, then propose
new issues that move the project forward.

Rules:
- Generate exactly {max_drafts} task proposals
- Each task must be concrete and implementable in 1-4 hours
- Don't duplicate existing open issues (check titles and descriptions)
- Prioritize tasks from the CURRENT phase in the roadmap
- Focus on unblocking other work first (dependencies, infrastructure)

For each task, output a JSON array of objects with:
- "title": imperative title ("Add X", "Fix Y", "Implement Z")
- "body": full issue body using the refined ticket structure from VISION.md
- "reasoning": one sentence explaining WHY this task matters now

Output ONLY valid JSON. No markdown fences. No preamble."""

# ─── Brainstorm Agent ────────────────────────────────────────

class BrainstormAgent:
    def __init__(self, github: GitHubClient, dry_run: bool = False):
        self.github = github
        self.llm = LLMClient()
        self.router = ModelRouter(ROUTING_PROFILE)
        self.cost = CostTracker(ceiling_usd=COST_CEILING_USD)
        self.vision = load_vision()
        self.dry_run = dry_run

    def _complete(self, task: str, system: str, message: str, max_tokens: int = 4000):
        model = self.router.get(task)
        response = self.llm.complete(model, system, message, max_tokens)
        
        class _Usage:
            def __init__(self, inp, out):
                self.input_tokens = inp
                self.output_tokens = out
        
        self.cost.record(model, _Usage(response.input_tokens, response.output_tokens),
                         agent="brainstorm", action=task)
        return response

    def check_pipeline_dry(self) -> bool:
        """Check if active pipeline (ready/needs-refinement) is below threshold."""
        issues = self.github.get_all_open_issues()
        active_labels = {LABEL_NEEDS_REFINEMENT, LABEL_READY, LABEL_IMPLEMENTING}
        
        active_count = 0
        for issue in issues:
            labels = {l.name for l in issue.labels}
            if labels & active_labels:
                active_count += 1
        
        log.info(f"📊 Pipeline status: {active_count} active issues (threshold: {BRAINSTORM_THRESHOLD})")
        return active_count < BRAINSTORM_THRESHOLD

    def run(self, force: bool = False):
        try:
            if not force and not self.check_pipeline_dry():
                log.info("✅ Pipeline is healthy. Skipping brainstorm.")
                return

            log.info("🧠 Entering BRAINSTORM mode")
            if not self.vision:
                log.error("Aborting: VISION.md is required for brainstorming.")
                return

            open_issues = self.github.get_all_open_issues()
            closed_issues = self.github.get_closed_issues(30)

            open_summary = "\n".join([f"- #{i.number} {i.title}" for i in open_issues])
            closed_summary = "\n".join([f"- #{i.number} [DONE] {i.title}" for i in closed_issues])

            response = self._complete(
                task="brainstorm",
                system=BRAINSTORM_SYSTEM.format(max_drafts=BRAINSTORM_MAX_DRAFTS),
                message=(
                    f"## VISION.md\n\n{self.vision}\n\n"
                    f"## Open Issues\n\n{open_summary or '(none)'}\n\n"
                    f"## Recently Completed\n\n{closed_summary or '(none)'}"
                )
            )

            if not self.cost.check_ceiling():
                log.warning("Cost ceiling reached. Aborting.")
                return

            raw = response.text.strip()
            if raw.startswith("```"):
                raw = raw.split("\n", 1)[1]
            if raw.endswith("```"):
                raw = raw.rsplit("```", 1)[0]
            
            drafts = json.loads(raw.strip())
            
            for d in drafts:
                log.info(f"  💡 Proposal: {d.get('title')} — {d.get('reasoning')}")

            created = self.github.create_draft_issues(drafts)
            
            if created:
                bullets = "\n".join([f"• #{n}: {t}" for n, t in created])
                msg = (
                    f"🧠 Brainstorm complete — created {len(created)} draft(s):\n"
                    f"{bullets}\n\n"
                    "Agent is now paused. Review and label as `needs-refinement` to proceed."
                )
                if not self.dry_run:
                    tg(msg)
                    state.set_state(AgentState.PAUSED)
            else:
                log.info("No drafts were created.")

        except Exception as e:
            log.error(f"Unhandled exception in BrainstormAgent: {e}", exc_info=True)

# ─── Main ────────────────────────────────────────────────────

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--force", action="store_true", help="Run even if pipeline is not dry")
    parser.add_argument("--dry-run", action="store_true", help="Log actions without touching GitHub")
    args = parser.parse_args()

    if not GITHUB_TOKEN or not REPO_NAME:
        log.error("Missing GITHUB_TOKEN or FOREMAN_REPO environment variables")
        sys.exit(1)

    gh_client = GitHubClient(GITHUB_TOKEN, REPO_NAME, dry_run=args.dry_run)
    agent = BrainstormAgent(gh_client, dry_run=args.dry_run)
    
    try:
        agent.run(force=args.force)
    except Exception as e:
        log.error(f"Critical failure in brainstorm loop: {e}")
        sys.exit(1)