# Ruff configuration
# For more info: https://beta.astral.sh/ruff/configuration/

line-length = 100
target-version = "py310"

[lint]
# Enable Pyflakes (`F`) and a subset of the pycodestyle (`E`)  codes by default.
# Also enable isort (`I`) and flake8-bugbear (`B`).
select = ["E4", "E7", "E9", "F", "B", "I"]
ignore = []

# Allow fix for all enabled rules (when `--fix`) is provided.
fixable = ["ALL"]
unfixable = []

# Allow unused variables when underscore-prefixed.
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[format]
# Use profile = "black" equivalent
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"
